# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'i2_EyeJump.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(220, 166)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.leftUPBtn = QtWidgets.QPushButton(Form)
        self.leftUPBtn.setObjectName("leftUPBtn")
        self.horizontalLayout_2.addWidget(self.leftUPBtn)
        self.rightUPBtn = QtWidgets.QPushButton(Form)
        self.rightUPBtn.setObjectName("rightUPBtn")
        self.horizontalLayout_2.addWidget(self.rightUPBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.leftDownBtn = QtWidgets.QPushButton(Form)
        self.leftDownBtn.setObjectName("leftDownBtn")
        self.horizontalLayout_4.addWidget(self.leftDownBtn)
        self.rightDownBtn = QtWidgets.QPushButton(Form)
        self.rightDownBtn.setObjectName("rightDownBtn")
        self.horizontalLayout_4.addWidget(self.rightDownBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.mutiBtn = QtWidgets.QPushButton(Form)
        self.mutiBtn.setObjectName("mutiBtn")
        self.verticalLayout.addWidget(self.mutiBtn)
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.leftUPBtn.setStyleSheet("QPushButton{background-color:rgb(34,139,34)}")
        self.rightUPBtn.setStyleSheet("QPushButton{background-color:rgb(255,193,37)}")
        self.leftDownBtn.setStyleSheet("QPushButton{background-color:rgb(178,34,34)}")
        self.rightDownBtn.setStyleSheet("QPushButton{background-color:rgb(0,191,255)}")
        self.mutiBtn.setStyleSheet("QPushButton{background-color:rgb(160,82,45)}")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "EyeJump"))
        self.label.setText(_translate("Form", "当前时间:"))
        self.label_2.setText(_translate("Form", "(可手动调整)"))
        self.leftUPBtn.setText(_translate("Form", "左上(木)"))
        self.rightUPBtn.setText(_translate("Form", "右上(金)"))
        self.leftDownBtn.setText(_translate("Form", "左下(火)"))
        self.rightDownBtn.setText(_translate("Form", "右下(水)"))
        self.mutiBtn.setText(_translate("Form", "多处同时动(土)"))
